task/SC-1100/node_js_12_deprecation
epcpower/stlib pull request #43
Opened 2023-04-05 20:00 UTC by Ezeigwefabian

## Jira Story
SC-1100

## About

1. actions/checkout@v2 -> actions/checkout@v3
2. actions/setup-python@v1 -> actions/setup-python@v4
3. aws-actions/configure-aws-credentials@v1 -> aws-actions/configure-aws-credentials@v1-node16

## Associated Pull Requests
N/A

## Update Changelog

*   [X] Changelog updated

## Reproduction Steps

## Validation

2023-04-05 22:11 UTC, gordon-epc requested changes

2023-04-05 22:11 UTC, gordon-epc commented on CHANGELOG.md
> +- SC-1100: Update actions versions to alleviate CI build warnings
Move this row to the top CI line (just above SC-798: ...)

2023-04-05 23:11 UTC, gordon-epc requested changes

2023-04-05 23:11 UTC, gordon-epc commented on .github/workflows/ci.yml
This line needs to be updated:
`uses: actions/upload-artifact@v2`
which is giving this warning message:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/upload-artifact@v2. For more information see: ...
```

2023-04-13 23:15 UTC, Fabian6781 commented on .github/workflows/ci.yml
I guess node16 shouldn't be there, i took it out and the build succeeded.

2023-04-14 18:51 UTC, gordon-epc requested changes

2023-04-14 18:51 UTC, gordon-epc commented on .github/workflows/ci.yml
Still has [the warning](https://github.com/epcpower/stlib/actions/runs/4694242793):

`Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`

You need to update:
`actions/upload-artifact@v2`

2023-05-08 23:32 UTC, gordon-epc requested changes

2023-05-08 23:32 UTC, gordon-epc commented on CHANGELOG.md
> +- SC-1100: Update ci.yml actions to fix poetry version issue
```suggestion
- SC-1100: Pin versions of all python packages for installing poetry
```

2023-05-09 18:21 UTC, gordon-epc approved these changes

2023-05-09 19:19 UTC, merged