Spike/sc 1929 m
epcpower/stlib pull request #50
Opened 2024-06-12 22:57 UTC by abnepc

## Jira Story
[SC-1929](https://epcpower.atlassian.net/browse/SC-1929)
## About
Investigate upgrading from `python3.7`
## Associated Pull Requests
* [m-bcu]()
* [m-pm]()
* [m-tcu]()

## Reproduction Steps
N/A
## Validation
Check that CI is using `python3.8`

[SC-1929]: https://epcpower.atlassian.net/browse/SC-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-12 23:26 UTC, gordon-epc requested changes

2024-06-12 23:26 UTC, gordon-epc commented on .github/workflows/ci.yml
For the regular scenario `ci.yml`, you edited two more lines. Let's keep them the same to avoid diff's later.

```
on:
  push:
    branches:
      - '**' #double star includes a '/'.  single star doesnt match a '/'
    tags:
      - '**' #double star includes a '/'.  single star doesnt match a '/'
```

2024-06-12 23:44 UTC, abnepc commented on .github/workflows/ci.yml
[2164a78](https://github.com/epcpower/stlib/pull/50/commits/2164a784354331ff712067e48baed6b072c39fb1)

2024-06-14 23:58 UTC, gordon-epc approved these changes

2024-06-14 23:58 UTC, gordon-epc approved these changes

2024-06-17 21:35 UTC, merged